import { createHash, scryptSync, timingSafeEqual } from 'node:crypto';

/**
 * `ADMIN_PASSWORD_HASH` comes in one of two formats:
 *
 *  - `scrypt:<salt hex>:<hash hex>` - generated by
 *    `node scripts/hash-admin-password.js <password>`. Salted and slow; use this.
 *  - a bare sha256 hex of the password - the legacy format, still accepted so
 *    existing environments keep working until the variable is rotated.
 *
 * Comparisons are constant time either way.
 */
export function verifyAdminPassword(password: string, storedHash: string): boolean {
	if (storedHash.startsWith('scrypt:')) {
		const [, saltHex, hashHex] = storedHash.split(':');

		if (!saltHex || !hashHex) {
			return false;
		}

		const salt = Buffer.from(saltHex, 'hex');
		const expected = Buffer.from(hashHex, 'hex');

		if (salt.length === 0 || expected.length === 0) {
			return false;
		}

		return timingSafeEqual(scryptSync(password, salt, expected.length), expected);
	}

	const expected = Buffer.from(storedHash, 'hex');
	const actual = createHash('sha256').update(password).digest();

	return expected.length === actual.length && timingSafeEqual(actual, expected);
}
