name: Lint check for PRs

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual trigger

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint
